### PR TITLE
Add FAQ item about bors and matrix items

### PR DESCRIPTION
**Pull request by TheNeikos**

### CODE REVIEW

**Comment by TheNeikos** [comment]
This is an issue that I've run into and recently fixed. Sharing this on the website might help the next one to run into this!

**Comment by TheNeikos** [comment]
Well, it looks like the github renderer and jekyll disagree on how to render code blocks in lists:

image


I am not sure what causes it to seize up like that

**Comment by matthiasbeyer** [comment]
Might be fixable by adding blank lines before and after the code blocks.

**Comment by notriddle** [comment]
Fixed it with https://github.com/bors-ng/bors-ng.github.io/commit/140f7715f3fa337fa24c023a6e643ff421689265

**Pull request merged**
