### PR TITLE
Focus and design

### PR DESCRIPTION
**Pull request by notriddle**
This should fix the way pagination gets handled (because we've almost reached the 10 post limit where it kicks in).

It also improves keyboard accessibility, by making sure that when you tab to something, it lights up enough to be noticeable what you focused.

### CODE REVIEW

**Comment by notriddle** [comment]
@Macarse want to look at this one, too?

**Comment by Macarse** [comment]
bors +r

**Comment by Macarse** [comment]
@notriddle ?

**Comment by notriddle** [comment]
bors r= @Macarse

**Pull request merged**
