### PR TITLE
TMIB-15

### PR DESCRIPTION
**Pull request by notriddle**
Want to help out with writing TMIB but don't have write access to the repo?
[Go here](https://github.com/bors-ng/bors-ng.github.io/blob/tmib-15/_posts/2018-04-01-tmib-15.md), then click the pencil button. That'll open a pull request for the in-progress edition of TMIB.

These steps can be done immediately after opening the TMIB pull request:

- [x] Fix the "Go here" link at the top of this pull request

- [x] Update the issue number in the `title:` part

- [x] Update the month in the `date:` part

- [x] Update the month in the `summary:`

- [x] Update the URL in the "last month" PR link

These steps need to be done as the month rolls along, though they should probably be proofread at the end:

- [x] Write the "notable additions" list

- [x] Write the "new contributors" list

- [x] Find a new featured user

And, these should be done last thing:

- [x] Update the PR count in the PR paragraph

- [x] Create, and link in, next month's PR, so that the published edition links to the next one

- [x] Write a few useful tidbits in the summary: part

And publish to third-party syndication services:

- [ElixirStatus](https://elixirstatus.com): copy the summary into their description box, followed by the post's URL; see <http://elixirstatus.com/p/doG2-ninth-monthly-bors-newsletter> for an example of how it should look
- [dev.to](https://dev.to): @notriddle should approve the draft after the RSS system pulls it in

### CODE REVIEW

**Comment by notriddle** [comment]
CC @RAOF @AlanGriffiths @Saviq

Is it okay to feature Mir in the newsletter? You've been using bors for a few months now. It'd also be nice if you reviewed the copy, both to make sure it's all accurate and that I'm not missing anything important.

**Comment by Saviq** [comment]
@notriddle sure, just let us know what to read.

**Comment by notriddle** [comment]
It's just [at the bottom of this page](https://github.com/bors-ng/bors-ng.github.io/blob/tmib-15/_posts/2018-04-01-tmib-15.md).

**Comment by Saviq** [comment]
@notriddle I've proposed a PR with a small tweak and an added bullet point. Hope it's OK.

Thanks!

**Pull request merged**
