### PR TITLE
TMIB-03

### PR DESCRIPTION
**Pull request by notriddle**
This Month in Bors checklist:

- [X] Update the issue number in the title area

- [X] Update the month in the date area

- [X] Update the month in the description area

- [X] Update the URL in the "last month" PR link

- [x] Update the PR count in the PR paragraph

- [x] Generate the "notable additions" list

- [x] Generate the "new contributors" list

- [x] Find a new featured user

- [ ] Find a screenshot

### CODE REVIEW

**Comment by notriddle** [comment]
Also, I'm nominating the [rust-fuzz](https://github.com/rust-fuzz) project for user-of-the-month, for the shear workout they're putting bors-ng through.

**Comment by notriddle** [comment]
@timvdalen, are you still using bors-ng? If so, do you mind saying what you're using it for (if it's proprietary, you can point at a public website or company instead of the GitHub repo)?

**Comment by timvdalen** [comment]
@notriddle Yeah we're still using it! My relative silence is due to the fact that I haven't seen a crash recently :)

We (@nubisonline, http://nub.is/) are using it in a couple of our larger projects.

Our main use case is this: We have quite a large number of feature branches being worked on simultaneously, and a deployment procedure that takes rather long (~40 mins).
We also have the policy that feature branches need to have the master merged into them before they can be merged back.

This results in a project manager having several tabs of PRs open during the day, merging one that is tested and green, then merging the master into the next one, waiting, merging that one once it becomes green, etc (with each of these steps taking the ~40 minutes).

With bors, we just mark all the ones that are green, and bors takes care of merging them in the right order and checking if merging master in it doesn't break things.

In fact, this had gotten so annoying that I had 'build a queuing system for PRs' rather high on my to do list when I found bors :)

One of the projects we're using it for is live here: https://privatelease.peugeot.nl/, https://privatelease.citroen.nl/, a car configure app for Peugeot/Citroën

**Comment by notriddle** [comment]
Awesome!

**Pull request merged**
