### PR TITLE
TMIB 21

### PR DESCRIPTION
**Pull request by notriddle**
Want to help out with writing TMIB but don't have write access to the repo?
[Go here](https://github.com/bors-ng/bors-ng.github.io/blob/tmib-21/_posts/2018-10-01-tmib-21.md), then click the pencil button. That'll open a pull request for the in-progress edition of TMIB.

These steps can be done immediately after opening the TMIB pull request:

- [x] Fix the "Go here" link at the top of this pull request

- [x] Update the issue number in the `title:` part

- [x] Update the month in the `date:` part

- [x] Update the month in the `summary:`

- [x] Update the URL in the "last month" PR link

These steps need to be done as the month rolls along, though they should probably be proofread at the end:

- [x] Write the "notable additions" list

- [x] Write the "new contributors" list

- [x] Find a new featured user

And, these should be done last thing:

- [x] Update the PR count in the PR paragraph

- [x] Create, and link in, next month's PR, so that the published edition links to the next one

- [x] Write a few useful tidbits in the summary: part

And publish to third-party syndication services:

- [ElixirStatus](https://elixirstatus.com): copy the summary into their description box, followed by the post's URL; see <http://elixirstatus.com/p/doG2-ninth-monthly-bors-newsletter> for an example of how it should look
- [dev.to](https://dev.to): @notriddle should approve the draft after the RSS system pulls it in
- [MailChimp](https://us19.admin.mailchimp.com/lists/): @notriddle should copy and paste the newsletter, then tweak the links

### CODE REVIEW

**Comment by notriddle** [comment]
@mythmon

Can I feature Mozilla's product delivery team this month?

**Comment by mythmon** [comment]
> Can I feature Mozilla's product delivery team this month?

That sounds great. Is there anything you need from us for that?

**Comment by notriddle** [comment]
Yeah, I would really like you to write up some copy describing what you do. I can try to figure it out from the Mozilla Wiki and GitHub repos themselves, but frankly, I can't even find a real description of what the "Product Delivery Team" specifically is, other than apparently delivery-console and normandy (both part of Firefox's A/B testing) as well as buildhub2, but specifically not TaskCluster itself, fall under it.

**Comment by notriddle** [comment]
Yeah, that's why I figure it might be better if you wrote it. There's a link at the top of the PR where you can make a sub-pull-request with a description that actually makes sense ([Shield](https://wiki.mozilla.org/Firefox/Shield) has a wiki page, while [mozilla wiki](https://wiki.mozilla.org/index.php?search=product+delivery&title=Special%3ASearch&go=Go) doesn't seem to have anything similar for Product Delivery).

**Comment by notriddle** [comment]
@mythmon How's it going?

**Pull request merged**
