### PR TITLE
TMIB-04

### PR DESCRIPTION
**Pull request by notriddle**
This Month in Bors checklist:

- [x] Update the issue number in the title area

- [x] Update the month in the date area

- [x] Update the month in the description area

- [x] Update the URL in the "last month" PR link

- [x] Update the PR count in the PR paragraph

- [x] Generate the "notable additions" list

- [x] Generate the "new contributors" list

- [x] Find a new featured user

- [ ] Find a screenshot

And, this should be the last thing you do:

- [x] Create, and link in, next month's PR

### CODE REVIEW

**Comment by Macarse** [comment]
my reading trip about bors started in the blogpost of the creator of bors, went through homu, the different forks and I am now reading this repo.

Do you mind writing a bit about:
 - Short summary of what are the different bors, homus, bors-ngs versions
 - Why did you start this project?
 - Why elixir?
 - Why did you implemented a batching strategy instead of parallel?
 - More questions to come as I read the code :)

**Comment by notriddle** [comment]
I wouldn't put this in the newsletter, so let's move this stuff into separate issues in the bors-ng.github.io repo. 😄

**Comment by Macarse** [comment]
@notriddle inside the readme?

**Comment by notriddle** [comment]
Interested in featuring [nix-rust/nix](https://github.com/nix-rust/nix) this month.

CC @kamalmarhubi

**Comment by kamalmarhubi** [comment]
@notriddle what does "featuring" mean / entail? I think we'd be fine with it after kicking the tires a bit more. Our conversion PR: https://github.com/nix-rust/nix/pull/584

**Comment by notriddle** [comment]
The other one I had in mind would be georust. @frewsxcv has been using bors-ng there since before it was called bors-ng and was still written in Rust.

**Comment by kamalmarhubi** [comment]
Perhaps that would be a better first fit. We really are just starting out with bors-ng, and haven't yet had a chance to see how the batching helps things.

**Comment by frewsxcv** [comment]
Feel free to feature GeoRust, bors-ng and all its predecessors have been helpful for us

**Pull request merged**
