### PR TITLE
TMIB-09

### PR DESCRIPTION
**Pull request by notriddle**
Want to help out with writing TMIB but don't have write access to the repo?
[Go here](https://github.com/bors-ng/bors-ng.github.io/blob/tmib-09/_posts/2017-10-01-tmib-09.md), then click the pencil button. That'll open a pull request for the in-progress edition of TMIB.

These steps can be done immediately after opening the TMIB pull request:

- [x] Fix the "Go here" link at the top of this pull request

- [x] Update the issue number in the `title:` part

- [x] Update the month in the `date:` part

- [x] Update the month in the `description:`

- [x] Update the URL in the "last month" PR link

These steps need to be done as the month rolls along, though they should probably be proofread at the end:

- [x] Generate the "notable additions" list

- [x] Generate the "new contributors" list

- [x] Find a new featured user

And, these should be done last thing:

- [x] Update the PR count in the PR paragraph

- [x] Create, and link in, next month's PR, so that the published edition links to the next one

### CODE REVIEW

**Comment by notriddle** [comment]
@kvark

Is it alright if [gfx-rs/gfx] is featured this month?

[gfx-rs/gfx]: https://github.com/gfx-rs/gfx

**Comment by kvark** [comment]
Absolutely:)

**Comment by notriddle** [comment]
@kvark Okay. Would you like to write the copy, or should I?

**Comment by kvark** [comment]
Does that sound good?

>This month’s featured user is gfx-rs, low-level graphics abstraction library in Rust.
>* Library aims to be the choice of cross-platform graphics development, serve as a basis for GPUWeb implementation, and provide the external C API for Vulkan portability initiative. See [We need to go lower](http://gfx-rs.github.io/2017/07/24/low-level.html) for more info.
>* The project has seen intensive development last month with over 50 merged pull requests having 130+ commits touching several thousand lines of code.
>* Main forces are concentrated around shaping up the low-level core API. The library structure has been shaken up, and a new vision is slowly materializing.

**Comment by notriddle** [comment]
Yep, LGTM.

**Pull request merged**
